name: Sync and update Github pages
description: Update the webfishing shitlist :3
runs:
    using: composite
    steps:
    -   name: Setup Python
        uses: actions/setup-python@5
        with:
            python-version: '3.12'
            cache: pip
    -   name: Sync banlist
        shell: bash
        run: |-
            python3 sync.py
            cat wall-of-shame.md
    # TODO - Needs to make a commit back to main, but we need a PAT and and env for that
