name: Create wall-of-shame.md

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed

jobs:
  create-shamemd:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      # Checkout the Code
      - name: Checkout Code
        uses: actions/checkout@v4
      # Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Sync Banlist
        shell: bash
        run: |-
            python shamemd.py
            cat wall-of-shame.md
      # Commit Changes
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: Automated shame.md update
          skip_checkout: true
          file_pattern: 'wall-of-shame.md'
      # Push Changes
      - name: Push Changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
